dist: trusty

language: node_js
node_js:
- stable

services:
- mongodb

install:
- wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
- npm install

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3

script:
- npm run coverage
- npm run check-coverage

after_success:
- npm run report-coverage

branches:
   only:
   - development

notifications:
    email:
      recipients:
        - 20079607@mail.wit.ie
      on_success: never
      on_failure: always

deploy:
  provider: heroku
  api_key: "244b3125-1456-4938-ac08-d1060760c6f7"
  app: beacon-mgmt
  on: development